files:
  - source: /locales/_pot
    ignore:
      - '*.php'
      - README
    translation: /locales/%two_letters_code%/%file_name%.po
  - source: /locales/en/help/
    translation: /locales/%two_letters_code%/help/%file_name%.html
  - source: /plugins/aboutConfig/locales/
    ignore:
      - '*.php'
    translation: /plugins/aboutConfig/locales/%two_letters_code%/%original_file_name%
