preserve_hierarchy: true
files:
  - source: /locales/en/
    ignore:
      - '*.html'
      - '*.php'
    translation: /locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        es-AR: es-ar
        pt-BR: pt-br
        zh-CN: zh-cn
        vls: nl
